# Generated by Django 3.2.13 on 2024-01-08 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonviewinfo',
            unique_together={('lesson', 'user')},
        ),
    ]
