# Generated by Django 3.2.13 on 2024-01-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_lessonviewinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonviewinfo',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='study.lesson'),
        ),
    ]
