# Generated by Django 3.2.13 on 2024-01-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_lessonviewinfo_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='product',
            new_name='products',
        ),
    ]
